spring:
  application.name: sample-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
  datasource:
    url: "jdbc:postgresql://localhost:5432/development"
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
springdoc.api-docs.path: /api-docs
